/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.empleados;

import conexion.Conexion;
import java.sql.ResultSet;
import conexion.Control;
import java.awt.BorderLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author awelo
 */
public class FrmEmpleados extends javax.swing.JFrame {

    private final Conexion conecta = new Conexion();
    private final Control con = new Control();
    private int permiso;
    private int usuario;
    private int activo;
    //private javax.swing.JFrame form;
    /**
     * Creates new form FrmEmpleados
     */
    public FrmEmpleados() {
        initComponents();
        activo=0;
        //form=frame;
    }
    
    public void setUsuario(int usuario){
        this.usuario=usuario;
    }
    
    public void mostrarDatos(int permiso){
        ResultSet obtenido = con.mostrarEmpleados(activo);
        try{
            String[] datos = new String[9];
            JPanel panel= new JPanel();
            BorderLayout capa= new BorderLayout();
            cappCapa.setLayout(capa);
            System.out.println(getPermiso());
            if(this.permiso<3){
                while(obtenido.next()){
                    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                    datos[0]=obtenido.getString(1);
                    datos[1]=obtenido.getString(2)+ " "+obtenido.getString(3);
                    datos[2]=obtenido.getString(4);
                    datos[3]=obtenido.getString(5);
                    datos[4]=obtenido.getString(6);
                    datos[5]=obtenido.getString(7);
                    datos[6]=obtenido.getString(8);
                    datos[7]=obtenido.getString(9);
                    datos[8]=obtenido.getString(10);
                    if(!datos[3].equals("3")){
                        if(datos[3].equals("1") || datos[0].equals(String.valueOf(usuario))){
                            PnlEmpleado empleado= new PnlEmpleado(this, permiso);
                            empleado.getMaximumSize();
                            empleado.setValores(datos);
                            empleado.SetUsuario(usuario);
                            panel.add(empleado, BorderLayout.CENTER);
                        }
                    }
                }
            }else{
                while(obtenido.next()){
                    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                    datos[0]=obtenido.getString(1);
                    datos[1]=obtenido.getString(2)+ " "+obtenido.getString(3);
                    datos[2]=obtenido.getString(4);
                    datos[3]=obtenido.getString(5);
                    datos[4]=obtenido.getString(6);
                    datos[5]=obtenido.getString(7);
                    datos[6]=obtenido.getString(8);
                    datos[7]=obtenido.getString(9);
                    PnlEmpleado empleado= new PnlEmpleado(this, permiso);
                    empleado.getMaximumSize();
                    empleado.setValores(datos);
                    panel.add(empleado, BorderLayout.CENTER);
                }
            }
            cappCapa.add(panel);
        } catch(java.sql.SQLException e){
            System.out.println("Error en la conexion "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cappCapa = new javax.swing.JLayeredPane();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chbxInactivos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout cappCapaLayout = new javax.swing.GroupLayout(cappCapa);
        cappCapa.setLayout(cappCapaLayout);
        cappCapaLayout.setHorizontalGroup(
            cappCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        cappCapaLayout.setVerticalGroup(
            cappCapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(cappCapa);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar:");

        chbxInactivos.setText("Mostrar Inactivos");
        chbxInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxInactivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(chbxInactivos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(chbxInactivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        DialNuevoEmpleado empleado= new DialNuevoEmpleado(this, true);
        empleado.setVisible(true);
        empleado.setLocationRelativeTo(null);
        mostrarDatos(permiso);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        try{
            ResultSet obtenido = conecta.mostrarEmpleadoFil(txtBuscar.getText(), permiso);
            String[] datos = new String[9];
            JPanel panel= new JPanel();
            BorderLayout capa= new BorderLayout();
            cappCapa.setLayout(capa);
            System.out.println(getPermiso());
            if(this.permiso<3){
                while(obtenido.next()){
                    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                    datos[0]=obtenido.getString(1);
                    datos[1]=obtenido.getString(2)+ " "+obtenido.getString(3);
                    datos[2]=obtenido.getString(4);
                    datos[3]=obtenido.getString(5);
                    datos[4]=obtenido.getString(6);
                    datos[5]=obtenido.getString(7);
                    datos[6]=obtenido.getString(8);
                    datos[7]=obtenido.getString(9);
                    datos[8]=obtenido.getString(10);
                    if(!datos[3].equals("3")){
                        if(datos[3].equals("1") || datos[0].equals(String.valueOf(usuario))){
                            PnlEmpleado empleado= new PnlEmpleado(this, permiso);
                            empleado.getMaximumSize();
                            empleado.setValores(datos);
                            empleado.SetUsuario(usuario);
                            panel.add(empleado, BorderLayout.CENTER);
                        }
                    }
                }
            }else{
                while(obtenido.next()){
                    panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
                    datos[0]=obtenido.getString(1);
                    datos[1]=obtenido.getString(2)+ " "+obtenido.getString(3);
                    datos[2]=obtenido.getString(4);
                    datos[3]=obtenido.getString(5);
                    datos[4]=obtenido.getString(6);
                    datos[5]=obtenido.getString(7);
                    datos[6]=obtenido.getString(8);
                    datos[7]=obtenido.getString(9);
                    PnlEmpleado empleado= new PnlEmpleado(this, permiso);
                    empleado.getMaximumSize();
                    empleado.setValores(datos);
                    panel.add(empleado, BorderLayout.CENTER);
                }
            }
            cappCapa.add(panel);
        } catch(java.sql.SQLException e){
            System.out.println("Error en la conexion "+e);
        }
            
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void chbxInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxInactivosActionPerformed
        // TODO add your handling code here:
        if(chbxInactivos.isSelected()){
            activo=1;
        }else{
            activo=0;
        }
        mostrarDatos(activo);
    }//GEN-LAST:event_chbxInactivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLayeredPane cappCapa;
    private javax.swing.JCheckBox chbxInactivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the permiso
     */
    public int getPermiso() {
        return permiso;
    }

    /**
     * @param permiso the permiso to set
     */
    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }
}
